// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-9j4VwoP3vaOrrJRQx3TVY5dlrRInoQ',
    appId: '1:586003398341:web:9b8e30d9f1730d160a7aac',
    messagingSenderId: '586003398341',
    projectId: 'routify-app-20f5c',
    authDomain: 'routify-app-20f5c.firebaseapp.com',
    databaseURL: 'https://routify-app-20f5c-default-rtdb.firebaseio.com',
    storageBucket: 'routify-app-20f5c.firebasestorage.app',
    measurementId: 'G-EYQCKL1KGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9deiHQGGLuG-18NQOk40ukJNbrZNvwm4',
    appId: '1:586003398341:android:2158c31ff35beac80a7aac',
    messagingSenderId: '586003398341',
    projectId: 'routify-app-20f5c',
    databaseURL: 'https://routify-app-20f5c-default-rtdb.firebaseio.com',
    storageBucket: 'routify-app-20f5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hW67vqa9_u8Flz98L12f17ntFABDUKM',
    appId: '1:586003398341:ios:859535b63886910e0a7aac',
    messagingSenderId: '586003398341',
    projectId: 'routify-app-20f5c',
    databaseURL: 'https://routify-app-20f5c-default-rtdb.firebaseio.com',
    storageBucket: 'routify-app-20f5c.firebasestorage.app',
    iosBundleId: 'com.example.routifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4hW67vqa9_u8Flz98L12f17ntFABDUKM',
    appId: '1:586003398341:ios:859535b63886910e0a7aac',
    messagingSenderId: '586003398341',
    projectId: 'routify-app-20f5c',
    databaseURL: 'https://routify-app-20f5c-default-rtdb.firebaseio.com',
    storageBucket: 'routify-app-20f5c.firebasestorage.app',
    iosBundleId: 'com.example.routifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-9j4VwoP3vaOrrJRQx3TVY5dlrRInoQ',
    appId: '1:586003398341:web:3b832905da1d0a2b0a7aac',
    messagingSenderId: '586003398341',
    projectId: 'routify-app-20f5c',
    authDomain: 'routify-app-20f5c.firebaseapp.com',
    databaseURL: 'https://routify-app-20f5c-default-rtdb.firebaseio.com',
    storageBucket: 'routify-app-20f5c.firebasestorage.app',
    measurementId: 'G-Z2KTBQ0SCG',
  );
}
